apiVersion: v1
kind: Service
metadata:
  name: mysql1
spec:
  selector:
    app: mysql1
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
    nodePort: 30306
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql1
  template:
    metadata:
      labels:
        app: mysql1
    spec:
      containers:
      - name: mysql1
        image: mysql/mysql-cluster
        env:
        - name: MYSQL_RANDOM_ROOT_PASSWORD
          value: "true"
#        - name: MYSQL_ROOT_PASSWORD
#          value: "P@ssw0rd"
#        - name: MYSQL_DATABASE
#          value: "mydb"
#        - name: MYSQL_USER
#          value: "user1"
#        - name: MYSQL_PASSWORD
#          value: "password1"
        args:
        - mysqld
        ports:
        - containerPort: 1186
        - containerPort: 3306
