#apiVersion: v1
#kind: Service
#metadata:
#  name: ndb1
#spec:
#  selector:
#    app: ndb1
#  ports:
#  - port: 8080
#    protocol: TCP
#    targetPort: 8080
#    nodePort: 30080
#  type: NodePort
#---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ndb1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ndb1
  template:
    metadata:
      labels:
        app: ndb1
    spec:
      containers:
      - name: ndb1
        image: mysql/mysql-cluster
        command: [ "ndbd" ]
#        args:
#        - ndbd
        ports:
        - containerPort: 1186
        - containerPort: 2202
        - containerPort: 3306
        - containerPort: 33060
